flowchart TD
  R[project_manager<br/>rank 5]
  R --> G1[Projects]
  G1 --> G1A0[List projects]
  G1 --> G1A1[View global dashboard]
  G1 --> G1A2[View personal dashboard (my tasks)]
  G1 --> G1A3[Cross-project search]
  G1 --> G1A4[Create project]
  G1 --> G1A5[View project detail]
  R --> G2[Members]
  G2 --> G2A0[List project members (+license flags)]
  G2 --> G2A1[Search addable users]
  G2 --> G2A2[Add member (auto-license; 409 if no seat)]
  G2 --> G2A3[Change member role]
  G2 --> G2A4[Remove member]
  R --> G3[Tasks]
  G3 --> G3A0[List / board / get / backlog tasks]
  G3 --> G3A1[Create task (+ optional assignee)]
  G3 --> G3A2[Full task update (PUT)]
  G3 --> G3A3[Change task status (transition/move)]
  G3 --> G3A4[Edit task checklist]
  G3 --> G3A5[Watch / unwatch task]
  R --> G4[Milestones]
  G4 --> G4A0[List milestones]
  R --> G5[Sprints]
  G5 --> G5A0[List sprints]
  G5 --> G5A1[Create / start / complete / plan / delete sprint]
  R --> G6[Comments]
  G6 --> G6A0[Read comments]
  G6 --> G6A1[Post comment (+ @mentions)]
  G6 --> G6A2[Edit / delete comment]
  R --> G7[Files]
  G7 --> G7A0[List files]
  G7 --> G7A1[Upload file]
  G7 --> G7A2[Delete file]
  R --> G8[Time]
  G8 --> G8A0[List time entries]
  G8 --> G8A1[Log time]
  G8 --> G8A2[Edit / delete time entry]
  R --> G9[Deliverables]
  G9 --> G9A0[List deliverables]
  G9 --> G9A1[Submit deliverable]
  G9 --> G9A2[Approve / reject deliverable]
  G9 --> G9A3[Delete deliverable]
  R --> G10[Events]
  G10 --> G10A0[List meetings/events]
  G10 --> G10A1[Create / update / delete event]
