flowchart TD
  R[developer<br/>rank 2]
  R --> G1[Projects]
  G1 --> G1A0[List projects]
  G1 --> G1A1[View global dashboard]
  G1 --> G1A2[View personal dashboard (my tasks)]
  G1 --> G1A3[Cross-project search]
  G1 --> G1A4[View project detail]
  G1 --> G1A5[View project dashboard tab]
  R --> G2[Members]
  G2 --> G2A0[List project members (+license flags)]
  R --> G3[Tasks]
  G3 --> G3A0[List / board / get / backlog tasks]
  G3 --> G3A1[Full task update (PUT)]
  G3 --> G3A2[Change task status (transition/move)]
  G3 --> G3A3[Edit task checklist]
  G3 --> G3A4[Watch / unwatch task]
  R --> G4[Milestones]
  G4 --> G4A0[List milestones]
  R --> G5[Sprints]
  G5 --> G5A0[List sprints]
  R --> G6[Comments]
  G6 --> G6A0[Read comments]
  G6 --> G6A1[Post comment (+ @mentions)]
  G6 --> G6A2[Edit / delete comment]
  R --> G7[Files]
  G7 --> G7A0[List files]
  G7 --> G7A1[Upload file]
  R --> G8[Time]
  G8 --> G8A0[List time entries]
  G8 --> G8A1[Log time]
  G8 --> G8A2[Edit / delete time entry]
  R --> G9[Deliverables]
  G9 --> G9A0[List deliverables]
  G9 --> G9A1[Submit deliverable]
  G9 --> G9A2[Approve / reject deliverable]
  R --> G10[Events]
  G10 --> G10A0[List meetings/events]
